background = #121810
foreground = #dce5d9
cursor-color = #86d469
selection-background = #364830
selection-foreground = #eff5ed

palette = 0=#0c110b
palette = 1=#ed856c
palette = 2=#74d45f
palette = 3=#e1d24f
palette = 4=#45a5e6
palette = 5=#ea8ac7
palette = 6=#6adcbe
palette = 7=#c3d0be
palette = 8=#5c6f55
palette = 9=#efa997
palette = 10=#a8e29b
palette = 11=#ece49f
palette = 12=#7cbeea
palette = 13=#eeadd6
palette = 14=#a8e8d7
palette = 15=#eff5ed
