general {
    col.active_border = rgb(86d469) rgb(ea8ac7) 45deg
    col.inactive_border = rgb(242e21)
}

decoration {
    shadow {
        color = rgba(080c07aa)
    }
}

group {
    col.border_active = rgb(86d469)
    col.border_inactive = rgb(242e21)

    groupbar {
        col.active = rgb(86d469)
        col.inactive = rgb(0c110b)
        text_color = rgb(dce5d9)
    }
}

misc {
    background_color = rgb(080c07)
}
