background #121810
foreground #dce5d9
cursor #86d469
selection_background #364830
selection_foreground #eff5ed
active_border_color #86d469
inactive_border_color #242e21
active_tab_background #86d469
active_tab_foreground #121810
inactive_tab_background #0c110b
inactive_tab_foreground #798e71

color0 #0c110b
color1 #ed856c
color2 #74d45f
color3 #e1d24f
color4 #45a5e6
color5 #ea8ac7
color6 #6adcbe
color7 #c3d0be
color8 #5c6f55
color9 #efa997
color10 #a8e29b
color11 #ece49f
color12 #7cbeea
color13 #eeadd6
color14 #a8e8d7
color15 #eff5ed
