return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#121810",
        dark_bg = "#0c110b",
        darker_bg = "#080c07",
        lighter_bg = "#242e21",
        fg = "#dce5d9",
        dark_fg = "#798e71",
        light_fg = "#c3d0be",
        bright_fg = "#eff5ed",
        muted = "#5c6f55",
        red = "#ed856c",
        yellow = "#e1d24f",
        orange = "#eca240",
        green = "#74d45f",
        cyan = "#6adcbe",
        blue = "#45a5e6",
        magenta = "#ea8ac7",
        brown = "#312917",
        bright_red = "#efa997",
        bright_yellow = "#ece49f",
        bright_green = "#a8e29b",
        bright_cyan = "#a8e8d7",
        bright_blue = "#7cbeea",
        bright_magenta = "#eeadd6",
        accent = "#86d469",
        selection = "#364830",
        cursor = "#eff5ed",
        selection_foreground = "#eff5ed",
        selection_background = "#364830",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
