background = #181010
foreground = #e5dad9
cursor-color = #ee8a83
selection-background = #483230
selection-foreground = #f5eeed

palette = 0=#110b0b
palette = 1=#ef827d
palette = 2=#85d358
palette = 3=#ebcc86
palette = 4=#8499ee
palette = 5=#ea8ac7
palette = 6=#6adcbe
palette = 7=#d0bfbe
palette = 8=#6f5755
palette = 9=#f1a7a4
palette = 10=#b1e096
palette = 11=#f1e0b9
palette = 12=#a5b5f1
palette = 13=#eeadd6
palette = 14=#a8e8d7
palette = 15=#f5eeed
