general {
    col.active_border = rgb(ee8a83) rgb(ea8ac7) 45deg
    col.inactive_border = rgb(2e2221)
}

decoration {
    shadow {
        color = rgba(0c0707aa)
    }
}

group {
    col.border_active = rgb(ee8a83)
    col.border_inactive = rgb(2e2221)

    groupbar {
        col.active = rgb(ee8a83)
        col.inactive = rgb(110b0b)
        text_color = rgb(e5dad9)
    }
}

misc {
    background_color = rgb(0c0707)
}
