background #181010
foreground #e5dad9
cursor #ee8a83
selection_background #483230
selection_foreground #f5eeed
active_border_color #ee8a83
inactive_border_color #2e2221
active_tab_background #ee8a83
active_tab_foreground #181010
inactive_tab_background #110b0b
inactive_tab_foreground #8e7371

color0 #110b0b
color1 #ef827d
color2 #85d358
color3 #ebcc86
color4 #8499ee
color5 #ea8ac7
color6 #6adcbe
color7 #d0bfbe
color8 #6f5755
color9 #f1a7a4
color10 #b1e096
color11 #f1e0b9
color12 #a5b5f1
color13 #eeadd6
color14 #a8e8d7
color15 #f5eeed
