return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#181010",
        dark_bg = "#110b0b",
        darker_bg = "#0c0707",
        lighter_bg = "#2e2221",
        fg = "#e5dad9",
        dark_fg = "#8e7371",
        light_fg = "#d0bfbe",
        bright_fg = "#f5eeed",
        muted = "#6f5755",
        red = "#ef827d",
        yellow = "#ebcc86",
        orange = "#f29d77",
        green = "#85d358",
        cyan = "#6adcbe",
        blue = "#8499ee",
        magenta = "#ea8ac7",
        brown = "#311e17",
        bright_red = "#f1a7a4",
        bright_yellow = "#f1e0b9",
        bright_green = "#b1e096",
        bright_cyan = "#a8e8d7",
        bright_blue = "#a5b5f1",
        bright_magenta = "#eeadd6",
        accent = "#ee8a83",
        selection = "#483230",
        cursor = "#f5eeed",
        selection_foreground = "#f5eeed",
        selection_background = "#483230",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
