mode = "dark"

accent = "#ebcc5e"
selection = "#484330"
muted = "#6f6955"

background = "#181610"
dark_background = "#11100b"
darker_background = "#0c0b07"
lighter_background = "#2e2b21"

foreground = "#e5e3d9"
dark_foreground = "#8e8771"
light_foreground = "#d0ccbe"
bright_foreground = "#f5f3ed"

red = "#ed856c"
yellow = "#e7d073"
orange = "#eda245"
green = "#85d358"
cyan = "#6adcbe"
blue = "#45a5e6"
magenta = "#ea8ac7"
brown = "#312417"

bright_red = "#efa997"
bright_yellow = "#f0e2af"
bright_green = "#b1e096"
bright_cyan = "#a8e8d7"
bright_blue = "#7cbeea"
bright_magenta = "#eeadd6"
