background = #181018
foreground = #e5d9e5
cursor-color = #ef89ea
selection-background = #483047
selection-foreground = #f5edf5

palette = 0=#110b11
palette = 1=#ef808f
palette = 2=#85d358
palette = 3=#ebcc86
palette = 4=#8499ee
palette = 5=#ea87df
palette = 6=#8fd3e5
palette = 7=#d0becf
palette = 8=#6f556e
palette = 9=#f2a6b0
palette = 10=#b1e096
palette = 11=#f1e0b9
palette = 12=#a5b5f1
palette = 13=#eeabe7
palette = 14=#b9e2ed
palette = 15=#f5edf5
