general {
    col.active_border = rgb(ef89ea) rgb(ea87df) 45deg
    col.inactive_border = rgb(2e212e)
}

decoration {
    shadow {
        color = rgba(0c070baa)
    }
}

group {
    col.border_active = rgb(ef89ea)
    col.border_inactive = rgb(2e212e)

    groupbar {
        col.active = rgb(ef89ea)
        col.inactive = rgb(110b11)
        text_color = rgb(e5d9e5)
    }
}

misc {
    background_color = rgb(0c070b)
}
