background #181018
foreground #e5d9e5
cursor #ef89ea
selection_background #483047
selection_foreground #f5edf5
active_border_color #ef89ea
inactive_border_color #2e212e
active_tab_background #ef89ea
active_tab_foreground #181018
inactive_tab_background #110b11
inactive_tab_foreground #8e718c

color0 #110b11
color1 #ef808f
color2 #85d358
color3 #ebcc86
color4 #8499ee
color5 #ea87df
color6 #8fd3e5
color7 #d0becf
color8 #6f556e
color9 #f2a6b0
color10 #b1e096
color11 #f1e0b9
color12 #a5b5f1
color13 #eeabe7
color14 #b9e2ed
color15 #f5edf5
