return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#181018",
        dark_bg = "#110b11",
        darker_bg = "#0c070b",
        lighter_bg = "#2e212e",
        fg = "#e5d9e5",
        dark_fg = "#8e718c",
        light_fg = "#d0becf",
        bright_fg = "#f5edf5",
        muted = "#6f556e",
        red = "#ef808f",
        yellow = "#ebcc86",
        orange = "#f29c77",
        green = "#85d358",
        cyan = "#8fd3e5",
        blue = "#8499ee",
        magenta = "#ea87df",
        brown = "#311817",
        bright_red = "#f2a6b0",
        bright_yellow = "#f1e0b9",
        bright_green = "#b1e096",
        bright_cyan = "#b9e2ed",
        bright_blue = "#a5b5f1",
        bright_magenta = "#eeabe7",
        accent = "#ef89ea",
        selection = "#483047",
        cursor = "#f5edf5",
        selection_foreground = "#f5edf5",
        selection_background = "#483047",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
