background = #101318
foreground = #d9dee5
cursor-color = #76a3ea
selection-background = #303948
selection-foreground = #edf0f5

palette = 0=#0b0d11
palette = 1=#ef808f
palette = 2=#65d670
palette = 3=#e1d24f
palette = 4=#6d9feb
palette = 5=#e189ea
palette = 6=#8cd3e4
palette = 7=#bec5d0
palette = 8=#555f6f
palette = 9=#f2a6b0
palette = 10=#9fe3a5
palette = 11=#ece49f
palette = 12=#96b9ee
palette = 13=#e8adee
palette = 14=#b7e2ec
palette = 15=#edf0f5
