general {
    col.active_border = rgb(76a3ea) rgb(e189ea) 45deg
    col.inactive_border = rgb(21262e)
}

decoration {
    shadow {
        color = rgba(07090caa)
    }
}

group {
    col.border_active = rgb(76a3ea)
    col.border_inactive = rgb(21262e)

    groupbar {
        col.active = rgb(76a3ea)
        col.inactive = rgb(0b0d11)
        text_color = rgb(d9dee5)
    }
}

misc {
    background_color = rgb(07090c)
}
