background #101318
foreground #d9dee5
cursor #76a3ea
selection_background #303948
selection_foreground #edf0f5
active_border_color #76a3ea
inactive_border_color #21262e
active_tab_background #76a3ea
active_tab_foreground #101318
inactive_tab_background #0b0d11
inactive_tab_foreground #717c8e

color0 #0b0d11
color1 #ef808f
color2 #65d670
color3 #e1d24f
color4 #6d9feb
color5 #e189ea
color6 #8cd3e4
color7 #bec5d0
color8 #555f6f
color9 #f2a6b0
color10 #9fe3a5
color11 #ece49f
color12 #96b9ee
color13 #e8adee
color14 #b7e2ec
color15 #edf0f5
