return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#101318",
        dark_bg = "#0b0d11",
        darker_bg = "#07090c",
        lighter_bg = "#21262e",
        fg = "#d9dee5",
        dark_fg = "#717c8e",
        light_fg = "#bec5d0",
        bright_fg = "#edf0f5",
        muted = "#555f6f",
        red = "#ef808f",
        yellow = "#e1d24f",
        orange = "#f29c77",
        green = "#65d670",
        cyan = "#8cd3e4",
        blue = "#6d9feb",
        magenta = "#e189ea",
        brown = "#311817",
        bright_red = "#f2a6b0",
        bright_yellow = "#ece49f",
        bright_green = "#9fe3a5",
        bright_cyan = "#b7e2ec",
        bright_blue = "#96b9ee",
        bright_magenta = "#e8adee",
        accent = "#76a3ea",
        selection = "#303948",
        cursor = "#edf0f5",
        selection_foreground = "#edf0f5",
        selection_background = "#303948",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
