background = #101818
foreground = #d9e5e5
cursor-color = #6cdad3
selection-background = #304846
selection-foreground = #edf5f4

palette = 0=#0b1111
palette = 1=#ed856c
palette = 2=#65d670
palette = 3=#e1d24f
palette = 4=#45a5e6
palette = 5=#e189ea
palette = 6=#63dbd5
palette = 7=#bed0cf
palette = 8=#556f6d
palette = 9=#efa997
palette = 10=#9fe3a5
palette = 11=#ece49f
palette = 12=#7cbeea
palette = 13=#e8adee
palette = 14=#a4e8e4
palette = 15=#edf5f4
