general {
    col.active_border = rgb(6cdad3) rgb(e189ea) 45deg
    col.inactive_border = rgb(212e2d)
}

decoration {
    shadow {
        color = rgba(070c0baa)
    }
}

group {
    col.border_active = rgb(6cdad3)
    col.border_inactive = rgb(212e2d)

    groupbar {
        col.active = rgb(6cdad3)
        col.inactive = rgb(0b1111)
        text_color = rgb(d9e5e5)
    }
}

misc {
    background_color = rgb(070c0b)
}
