background #101818
foreground #d9e5e5
cursor #6cdad3
selection_background #304846
selection_foreground #edf5f4
active_border_color #6cdad3
inactive_border_color #212e2d
active_tab_background #6cdad3
active_tab_foreground #101818
inactive_tab_background #0b1111
inactive_tab_foreground #718e8c

color0 #0b1111
color1 #ed856c
color2 #65d670
color3 #e1d24f
color4 #45a5e6
color5 #e189ea
color6 #63dbd5
color7 #bed0cf
color8 #556f6d
color9 #efa997
color10 #9fe3a5
color11 #ece49f
color12 #7cbeea
color13 #e8adee
color14 #a4e8e4
color15 #edf5f4
