return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#101818",
        dark_bg = "#0b1111",
        darker_bg = "#070c0b",
        lighter_bg = "#212e2d",
        fg = "#d9e5e5",
        dark_fg = "#718e8c",
        light_fg = "#bed0cf",
        bright_fg = "#edf5f4",
        muted = "#556f6d",
        red = "#ed856c",
        yellow = "#e1d24f",
        orange = "#eca240",
        green = "#65d670",
        cyan = "#63dbd5",
        blue = "#45a5e6",
        magenta = "#e189ea",
        brown = "#312917",
        bright_red = "#efa997",
        bright_yellow = "#ece49f",
        bright_green = "#9fe3a5",
        bright_cyan = "#a4e8e4",
        bright_blue = "#7cbeea",
        bright_magenta = "#e8adee",
        accent = "#6cdad3",
        selection = "#304846",
        cursor = "#edf5f4",
        selection_foreground = "#edf5f4",
        selection_background = "#304846",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
