background = #181610
foreground = #e5e3d9
cursor-color = #ebcc5e
selection-background = #484330
selection-foreground = #f5f3ed

palette = 0=#11100b
palette = 1=#ed856c
palette = 2=#85d358
palette = 3=#e7d073
palette = 4=#45a5e6
palette = 5=#ea8ac7
palette = 6=#6adcbe
palette = 7=#d0ccbe
palette = 8=#6f6955
palette = 9=#efa997
palette = 10=#b1e096
palette = 11=#f0e2af
palette = 12=#7cbeea
palette = 13=#eeadd6
palette = 14=#a8e8d7
palette = 15=#f5f3ed
