background #181610
foreground #e5e3d9
cursor #ebcc5e
selection_background #484330
selection_foreground #f5f3ed
active_border_color #ebcc5e
inactive_border_color #2e2b21
active_tab_background #ebcc5e
active_tab_foreground #181610
inactive_tab_background #11100b
inactive_tab_foreground #8e8771

color0 #11100b
color1 #ed856c
color2 #85d358
color3 #e7d073
color4 #45a5e6
color5 #ea8ac7
color6 #6adcbe
color7 #d0ccbe
color8 #6f6955
color9 #efa997
color10 #b1e096
color11 #f0e2af
color12 #7cbeea
color13 #eeadd6
color14 #a8e8d7
color15 #f5f3ed
