return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#181610",
        dark_bg = "#11100b",
        darker_bg = "#0c0b07",
        lighter_bg = "#2e2b21",
        fg = "#e5e3d9",
        dark_fg = "#8e8771",
        light_fg = "#d0ccbe",
        bright_fg = "#f5f3ed",
        muted = "#6f6955",
        red = "#ed856c",
        yellow = "#e7d073",
        orange = "#eda245",
        green = "#85d358",
        cyan = "#6adcbe",
        blue = "#45a5e6",
        magenta = "#ea8ac7",
        brown = "#312417",
        bright_red = "#efa997",
        bright_yellow = "#f0e2af",
        bright_green = "#b1e096",
        bright_cyan = "#a8e8d7",
        bright_blue = "#7cbeea",
        bright_magenta = "#eeadd6",
        accent = "#ebcc5e",
        selection = "#484330",
        cursor = "#f5f3ed",
        selection_foreground = "#f5f3ed",
        selection_background = "#484330",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
