background = #131315
foreground = #dddee1
cursor-color = #c9ced6
selection-background = #383b40
selection-foreground = #f0f1f2

palette = 0=#0d0e0f
palette = 1=#ef837f
palette = 2=#71d562
palette = 3=#e7cf71
palette = 4=#6c9feb
palette = 5=#ea87dd
palette = 6=#63dbd7
palette = 7=#c4c6ca
palette = 8=#5e6166
palette = 9=#f1a7a4
palette = 10=#a6e39d
palette = 11=#efe2af
palette = 12=#95b8ee
palette = 13=#eeace5
palette = 14=#a4e8e5
palette = 15=#f0f1f2
