general {
    col.active_border = rgb(c9ced6) rgb(ea87dd) 45deg
    col.inactive_border = rgb(26272a)
}

decoration {
    shadow {
        color = rgba(08090aaa)
    }
}

group {
    col.border_active = rgb(c9ced6)
    col.border_inactive = rgb(26272a)

    groupbar {
        col.active = rgb(c9ced6)
        col.inactive = rgb(0d0e0f)
        text_color = rgb(dddee1)
    }
}

misc {
    background_color = rgb(08090a)
}
