background #131315
foreground #dddee1
cursor #c9ced6
selection_background #383b40
selection_foreground #f0f1f2
active_border_color #c9ced6
inactive_border_color #26272a
active_tab_background #c9ced6
active_tab_foreground #131315
inactive_tab_background #0d0e0f
inactive_tab_foreground #7b7e84

color0 #0d0e0f
color1 #ef837f
color2 #71d562
color3 #e7cf71
color4 #6c9feb
color5 #ea87dd
color6 #63dbd7
color7 #c4c6ca
color8 #5e6166
color9 #f1a7a4
color10 #a6e39d
color11 #efe2af
color12 #95b8ee
color13 #eeace5
color14 #a4e8e5
color15 #f0f1f2
