return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#131315",
        dark_bg = "#0d0e0f",
        darker_bg = "#08090a",
        lighter_bg = "#26272a",
        fg = "#dddee1",
        dark_fg = "#7b7e84",
        light_fg = "#c4c6ca",
        bright_fg = "#f0f1f2",
        muted = "#5e6166",
        red = "#ef837f",
        yellow = "#e7cf71",
        orange = "#ef9f61",
        green = "#71d562",
        cyan = "#63dbd7",
        blue = "#6c9feb",
        magenta = "#ea87dd",
        brown = "#312017",
        bright_red = "#f1a7a4",
        bright_yellow = "#efe2af",
        bright_green = "#a6e39d",
        bright_cyan = "#a4e8e5",
        bright_blue = "#95b8ee",
        bright_magenta = "#eeace5",
        accent = "#c9ced6",
        selection = "#383b40",
        cursor = "#f0f1f2",
        selection_foreground = "#f0f1f2",
        selection_background = "#383b40",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
