background = #181013
foreground = #e5d9de
cursor-color = #ed92b5
selection-background = #483039
selection-foreground = #f5edf0

palette = 0=#110b0d
palette = 1=#ef828d
palette = 2=#85d358
palette = 3=#ebcc86
palette = 4=#8499ee
palette = 5=#ea89cd
palette = 6=#8fd3e5
palette = 7=#d0bec5
palette = 8=#6f555f
palette = 9=#f2a6ae
palette = 10=#b1e096
palette = 11=#f1e0b9
palette = 12=#a5b5f1
palette = 13=#eeaddb
palette = 14=#b9e2ed
palette = 15=#f5edf0
