general {
    col.active_border = rgb(ed92b5) rgb(ea89cd) 45deg
    col.inactive_border = rgb(2e2126)
}

decoration {
    shadow {
        color = rgba(0c0709aa)
    }
}

group {
    col.border_active = rgb(ed92b5)
    col.border_inactive = rgb(2e2126)

    groupbar {
        col.active = rgb(ed92b5)
        col.inactive = rgb(110b0d)
        text_color = rgb(e5d9de)
    }
}

misc {
    background_color = rgb(0c0709)
}
