background #181013
foreground #e5d9de
cursor #ed92b5
selection_background #483039
selection_foreground #f5edf0
active_border_color #ed92b5
inactive_border_color #2e2126
active_tab_background #ed92b5
active_tab_foreground #181013
inactive_tab_background #110b0d
inactive_tab_foreground #8e717c

color0 #110b0d
color1 #ef828d
color2 #85d358
color3 #ebcc86
color4 #8499ee
color5 #ea89cd
color6 #8fd3e5
color7 #d0bec5
color8 #6f555f
color9 #f2a6ae
color10 #b1e096
color11 #f1e0b9
color12 #a5b5f1
color13 #eeaddb
color14 #b9e2ed
color15 #f5edf0
