return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#181013",
        dark_bg = "#110b0d",
        darker_bg = "#0c0709",
        lighter_bg = "#2e2126",
        fg = "#e5d9de",
        dark_fg = "#8e717c",
        light_fg = "#d0bec5",
        bright_fg = "#f5edf0",
        muted = "#6f555f",
        red = "#ef828d",
        yellow = "#ebcc86",
        orange = "#f29c77",
        green = "#85d358",
        cyan = "#8fd3e5",
        blue = "#8499ee",
        magenta = "#ea89cd",
        brown = "#311a17",
        bright_red = "#f2a6ae",
        bright_yellow = "#f1e0b9",
        bright_green = "#b1e096",
        bright_cyan = "#b9e2ed",
        bright_blue = "#a5b5f1",
        bright_magenta = "#eeaddb",
        accent = "#ed92b5",
        selection = "#483039",
        cursor = "#f5edf0",
        selection_foreground = "#f5edf0",
        selection_background = "#483039",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
