background #181310
foreground #e5ded9
cursor #eea265
selection_background #483b30
selection_foreground #f5f1ed
active_border_color #eea265
inactive_border_color #2e2721
active_tab_background #eea265
active_tab_foreground #181310
inactive_tab_background #110e0b
inactive_tab_foreground #8e7e71

color0 #110e0b
color1 #ed866f
color2 #85d358
color3 #ebcc86
color4 #8499ee
color5 #ea8ac7
color6 #6adcbe
color7 #d0c6be
color8 #6f6155
color9 #f0a999
color10 #b1e096
color11 #f1e0b9
color12 #a5b5f1
color13 #eeadd6
color14 #a8e8d7
color15 #f5f1ed
