return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#181310",
        dark_bg = "#110e0b",
        darker_bg = "#0c0907",
        lighter_bg = "#2e2721",
        fg = "#e5ded9",
        dark_fg = "#8e7e71",
        light_fg = "#d0c6be",
        bright_fg = "#f5f1ed",
        muted = "#6f6155",
        red = "#ed866f",
        yellow = "#ebcc86",
        orange = "#ef9f61",
        green = "#85d358",
        cyan = "#6adcbe",
        blue = "#8499ee",
        magenta = "#ea8ac7",
        brown = "#312117",
        bright_red = "#f0a999",
        bright_yellow = "#f1e0b9",
        bright_green = "#b1e096",
        bright_cyan = "#a8e8d7",
        bright_blue = "#a5b5f1",
        bright_magenta = "#eeadd6",
        accent = "#eea265",
        selection = "#483b30",
        cursor = "#f5f1ed",
        selection_foreground = "#f5f1ed",
        selection_background = "#483b30",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
