background = #131018
foreground = #ded9e5
cursor-color = #ba9bed
selection-background = #393048
selection-foreground = #f0edf5

palette = 0=#0d0b11
palette = 1=#ef808f
palette = 2=#65d670
palette = 3=#ebcc86
palette = 4=#8499ee
palette = 5=#e189ea
palette = 6=#8fd3e5
palette = 7=#c5bed0
palette = 8=#5f556f
palette = 9=#f2a6b0
palette = 10=#9fe3a5
palette = 11=#f1e0b9
palette = 12=#a5b5f1
palette = 13=#e8adee
palette = 14=#b9e2ed
palette = 15=#f0edf5
