general {
    col.active_border = rgb(ba9bed) rgb(e189ea) 45deg
    col.inactive_border = rgb(26212e)
}

decoration {
    shadow {
        color = rgba(09070caa)
    }
}

group {
    col.border_active = rgb(ba9bed)
    col.border_inactive = rgb(26212e)

    groupbar {
        col.active = rgb(ba9bed)
        col.inactive = rgb(0d0b11)
        text_color = rgb(ded9e5)
    }
}

misc {
    background_color = rgb(09070c)
}
