background #131018
foreground #ded9e5
cursor #ba9bed
selection_background #393048
selection_foreground #f0edf5
active_border_color #ba9bed
inactive_border_color #26212e
active_tab_background #ba9bed
active_tab_foreground #131018
inactive_tab_background #0d0b11
inactive_tab_foreground #7c718e

color0 #0d0b11
color1 #ef808f
color2 #65d670
color3 #ebcc86
color4 #8499ee
color5 #e189ea
color6 #8fd3e5
color7 #c5bed0
color8 #5f556f
color9 #f2a6b0
color10 #9fe3a5
color11 #f1e0b9
color12 #a5b5f1
color13 #e8adee
color14 #b9e2ed
color15 #f0edf5
