return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#131018",
        dark_bg = "#0d0b11",
        darker_bg = "#09070c",
        lighter_bg = "#26212e",
        fg = "#ded9e5",
        dark_fg = "#7c718e",
        light_fg = "#c5bed0",
        bright_fg = "#f0edf5",
        muted = "#5f556f",
        red = "#ef808f",
        yellow = "#ebcc86",
        orange = "#f29c77",
        green = "#65d670",
        cyan = "#8fd3e5",
        blue = "#8499ee",
        magenta = "#e189ea",
        brown = "#311817",
        bright_red = "#f2a6b0",
        bright_yellow = "#f1e0b9",
        bright_green = "#9fe3a5",
        bright_cyan = "#b9e2ed",
        bright_blue = "#a5b5f1",
        bright_magenta = "#e8adee",
        accent = "#ba9bed",
        selection = "#393048",
        cursor = "#f0edf5",
        selection_foreground = "#f0edf5",
        selection_background = "#393048",
      },
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "aether",
    },
  },
}
